### ISSUE TITLE
Work without Auth Token

### ISSUE THREAD

**Issue by deidyomega** [foxy999/PiHoleWidgets#10]
When I check my auth token, it says,

"No password set".  

But if I dont put in an auth token, it says, "Check Auth Token"

This is easily fixable by stating in the documentation if you dont have a password use "*" as your auth token.  It still reads fine, but doesn't give you an error about auth tokens.

**Comment by foxy999** [comment]
That's not an error it's a message to let the user know that some parts of the widget needs the API Token
