### ISSUE TITLE
Reconfigure after install - settings seem stick across installs 

### ISSUE THREAD

**Issue by atiensivu** [foxy999/PiHoleWidgets#12]
How do I delete the Pi-Hole IP setting? I put in the wrong IP and now I'm stuck with no way to reconfigure it, even after reinstall. :(

**Comment by atiensivu** [comment]
Found it - C:\Users\[profile]\Pihole Widget\settings.json

**Comment by foxy999** [comment]
You can change reopen the settings UI by clicking on the copyright label.
